# 6 Pandas的函数应用

In [2]:
import pandas as pd
import numpy as np
# Numpy ufunc 函数，randn跟的是维数
df = pd.DataFrame(np.random.randn(5,4) - 1)
print(df)

print(np.abs(df)) #绝对值

          0         1         2         3
0 -0.655203  0.656585 -0.360487 -1.655061
1 -1.886135  0.389399 -1.292955 -0.363429
2 -1.582728 -0.672817  0.825079 -0.917518
3 -0.335551 -0.560750 -0.303902 -1.516986
4 -1.477920 -1.550311 -0.937898 -2.366345
          0         1         2         3
0  0.655203  0.656585  0.360487  1.655061
1  1.886135  0.389399  1.292955  0.363429
2  1.582728  0.672817  0.825079  0.917518
3  0.335551  0.560750  0.303902  1.516986
4  1.477920  1.550311  0.937898  2.366345

In [3]:
#apply默认作用在列上,x是每一列,因为axis=0
print(df.apply(lambda x : x.max()))

0   -0.335551
1    0.656585
2    0.825079
3   -0.363429
dtype: float64

In [4]:
#apply作用在行上
print(df.apply(lambda x : x.max(), axis=1))

0    0.656585
1    0.389399
2    0.825079
3   -0.303902
4   -0.937898
dtype: float64

In [5]:
# 使用applymap应用到每个数据
print(df.map(lambda x : '%.2f' % x))
df.dtypes

       0      1      2      3
0  -0.66   0.66  -0.36  -1.66
1  -1.89   0.39  -1.29  -0.36
2  -1.58  -0.67   0.83  -0.92
3  -0.34  -0.56  -0.30  -1.52
4  -1.48  -1.55  -0.94  -2.37

0    float64
1    float64
2    float64
3    float64
dtype: object

In [6]:
type('%.2f' % 1.3456)

str

## 6.4 索引排序（不重要）

In [7]:
# Series
print(np.random.randint(5, size=5))
print('-'*50)
s4 = pd.Series(range(10, 15), index = np.random.randint(5, size=5)) #索引随机生成
print(s4)
print('-'*50)
# 索引排序,sort_index返回一个新的排好索引的series
print(s4.sort_index())
print(s4)
# s4.loc[0:3]  loc索引值不唯一时直接报错
print(s4.iloc[0:3])
s4[0:3]  #默认用的位置索引

[1 3 0 0 3]
--------------------------------------------------
0    10
0    11
2    12
1    13
1    14
dtype: int64
--------------------------------------------------
0    10
0    11
1    13
1    14
2    12
dtype: int64
0    10
0    11
2    12
1    13
1    14
dtype: int64
0    10
0    11
2    12
dtype: int64

0    10
0    11
2    12
dtype: int64

In [8]:
# s4.loc[1:2] #loc索引值唯一时可以切片

In [9]:
# DataFrame
df4 = pd.DataFrame(np.random.randn(5, 5),
                   index=np.random.randint(5, size=5),
                   columns=np.random.randint(5, size=5))
print(df4)
#轴零是行索引排序
df4_isort = df4.sort_index(axis=0, ascending=False)
print(df4_isort)

          1         1         0         1         3
0 -1.204539  1.115370  0.855956  1.563919  1.142285
1 -0.030946 -0.796114 -2.376079  1.365585 -1.242412
2  0.982725  0.227101 -1.749823 -1.729885  0.336356
1  3.133516 -1.130025  0.166902 -0.764198  1.491518
0  0.952818  0.286646  0.029056  0.055710 -0.281180
          1         1         0         1         3
2  0.982725  0.227101 -1.749823 -1.729885  0.336356
1  3.133516 -1.130025  0.166902 -0.764198  1.491518
1 -0.030946 -0.796114 -2.376079  1.365585 -1.242412
0 -1.204539  1.115370  0.855956  1.563919  1.142285
0  0.952818  0.286646  0.029056  0.055710 -0.281180

In [10]:
#轴1是列索引排序
df4_isort = df4.sort_index(axis=1, ascending=True)
print(df4_isort)

          0         1         1         1         3
0  0.855956 -1.204539  1.115370  1.563919  1.142285
1 -2.376079 -0.030946 -0.796114  1.365585 -1.242412
2 -1.749823  0.982725  0.227101 -1.729885  0.336356
1  0.166902  3.133516 -1.130025 -0.764198  1.491518
0  0.029056  0.952818  0.286646  0.055710 -0.281180

# 6.5 按值排序（机器学习，深度学习不重要，数据分析才需要）

In [11]:
# 按值排序,by后是column的值
import random
l=[random.randint(0,100) for i in range(24)] #生成24个随机数
df4 = pd.DataFrame(np.array(l).reshape(6,4)) #生成6行4列的dataframe
# print(df4) #查看数据,ndarray
# print('-'*50)
print(df4)
print('-'*50)
#按轴零排序，by后是列名,交换的是行
df4_vsort = df4.sort_values(by=3,axis=0, ascending=False) #寻找的是columns里的3,重要
print(df4_vsort)

    0   1   2   3
0  49  23  77  46
1  64  62  48  99
2  59  45  90  29
3  38  92  12  61
4  95   5  27  60
5  59  75  35  32
--------------------------------------------------
    0   1   2   3
1  64  62  48  99
3  38  92  12  61
4  95   5  27  60
0  49  23  77  46
5  59  75  35  32
2  59  45  90  29

In [12]:
#按轴1排序，by后行索引名，交换的是列
df4_vsort = df4.sort_values(by=3,axis=1, ascending=False) #寻找的是index里的3
print(df4_vsort)

    1   3   0   2
0  23  46  49  77
1  62  99  64  48
2  45  29  59  90
3  92  61  38  12
4   5  60  95  27
5  75  32  59  35

# 6.6 处理缺失数据（重要）

In [13]:
df_data = pd.DataFrame([np.random.randn(3), [1., 2., np.nan],
                       [np.nan, 4., np.nan], [1., 2., 3.]])
print(df_data.head())

          0         1         2
0 -0.151889 -0.345591 -0.275731
1  1.000000  2.000000       NaN
2       NaN  4.000000       NaN
3  1.000000  2.000000  3.000000

In [14]:
df_data.iloc[2,0]

np.float64(nan)

In [15]:
#isnull来判断是否有空的数据
print(df_data.isnull())

       0      1      2
0  False  False  False
1  False  False   True
2   True  False   True
3  False  False  False

In [16]:
#帮我计算df_data缺失率
print(df_data.isnull().sum()/len(df_data))

0    0.25
1    0.00
2    0.50
dtype: float64

## 删除缺失数据

In [17]:
#默认一个样本，任何一个特征缺失，就删除
#inplace True是修改的是原有的df
#subset=[0]是指按第一列来删除,第一列有空值就删除对应的行
print(df_data.dropna(subset=[0]))
# df_data

          0         1         2
0 -0.151889 -0.345591 -0.275731
1  1.000000  2.000000       NaN
3  1.000000  2.000000  3.000000

In [18]:
df_data

          0         1         2
0 -0.151889 -0.345591 -0.275731
1  1.000000  2.000000       NaN
2       NaN  4.000000       NaN
3  1.000000  2.000000  3.000000

In [19]:
#用的不多，用在某个特征缺失太多时，才会进行删除
print(df_data.dropna(axis=1))  #某列由nan就删除该列

          1
0 -0.345591
1  2.000000
2  4.000000
3  2.000000

In [20]:
df_data

          0         1         2
0 -0.151889 -0.345591 -0.275731
1  1.000000  2.000000       NaN
2       NaN  4.000000       NaN
3  1.000000  2.000000  3.000000

## 填充缺失数据

In [21]:
#均值，中位数，众数填充

In [22]:
#给零列的空值填为-100，按特征（按列）去填充
print(df_data.iloc[:,0].fillna(-100.))
df_data

0     -0.151889
1      1.000000
2   -100.000000
3      1.000000
Name: 0, dtype: float64

          0         1         2
0 -0.151889 -0.345591 -0.275731
1  1.000000  2.000000       NaN
2       NaN  4.000000       NaN
3  1.000000  2.000000  3.000000

In [23]:
#依次拿到每一列
for i in df_data.columns:
    print(df_data.loc[:,i])

0   -0.151889
1    1.000000
2         NaN
3    1.000000
Name: 0, dtype: float64
0   -0.345591
1    2.000000
2    4.000000
3    2.000000
Name: 1, dtype: float64
0   -0.275731
1         NaN
2         NaN
3    3.000000
Name: 2, dtype: float64

In [24]:
df_data.iloc[:,0].fillna(-100.,inplace=True) #inplace=True后面会被删除

C:\Users\WangZhiao\AppData\Local\Temp\ipykernel_62752\3150007156.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_data.iloc[:,0].fillna(-100.,inplace=True) #inplace=True后面会被删除

In [25]:
df_data.iloc[:,2]=df_data.iloc[:,2].fillna(df_data.iloc[:,2].mean()) #用均值填充空值

In [26]:
df_data

            0         1         2
0   -0.151889 -0.345591 -0.275731
1    1.000000  2.000000  1.362135
2 -100.000000  4.000000  1.362135
3    1.000000  2.000000  3.000000