# 10 数据连接

In [4]:
import pandas as pd
import numpy as np

df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data1' : np.random.randint(0,10,7)})
df_obj2 = pd.DataFrame({'key': ['a', 'b' ,'d'],
                        'data2' : np.random.randint(0,10,3)})

print(df_obj1)
print('-'*50)
print(df_obj2)

  key  data1
0   b      2
1   b      6
2   a      1
3   c      2
4   a      9
5   a      3
6   b      1
--------------------------------------------------
  key  data2
0   a      0
1   b      8
2   d      2

In [5]:
#默认连接使用相同的列名，连接方式是内连接
pd.merge(df_obj1, df_obj2)

  key  data1  data2
0   b      2      8
1   b      6      8
2   a      1      0
3   a      9      0
4   a      3      0
5   b      1      8

In [3]:
#左df和右df都拿索引连接
pd.merge(df_obj1, df_obj2,left_index=True,right_index=True)

  key_x  data1 key_y  data2
0     b      6     a      2
1     b      4     b      3
2     a      5     d      9

In [11]:
#左表和右表都拿key列来连接
pd.merge(df_obj1, df_obj2, on='key')

  key  data1  data2
0   b      2      8
1   b      6      8
2   a      1      0
3   a      9      0
4   a      3      0
5   b      1      8

In [13]:
# 更改列名
df_obj1 = df_obj1.rename(columns={'key':'key1'})
df_obj2 = df_obj2.rename(columns={'key':'key2'})

In [14]:
df_obj1

  key1  data1
0    b      2
1    b      6
2    a      1
3    c      2
4    a      9
5    a      3
6    b      1

In [16]:
df_obj2

  key2  data2
0    a      0
1    b      8
2    d      2

In [17]:
#左表以key1来连接，右表以key2来连接
pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2',how='outer')

  key1  data1 key2  data2
0    a    1.0    a    0.0
1    a    9.0    a    0.0
2    a    3.0    a    0.0
3    b    2.0    b    8.0
4    b    6.0    b    8.0
5    b    1.0    b    8.0
6    c    2.0  NaN    NaN
7  NaN    NaN    d    2.0

In [19]:
#全外连接
pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2', how='outer')  #全外连接

  key1  data1 key2  data2
0    a    1.0    a    0.0
1    a    9.0    a    0.0
2    a    3.0    a    0.0
3    b    2.0    b    8.0
4    b    6.0    b    8.0
5    b    1.0    b    8.0
6    c    2.0  NaN    NaN
7  NaN    NaN    d    2.0

In [20]:
#left join 等价于 left  join
pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2', how='left')

  key1  data1 key2  data2
0    b      2    b    8.0
1    b      6    b    8.0
2    a      1    a    0.0
3    c      2  NaN    NaN
4    a      9    a    0.0
5    a      3    a    0.0
6    b      1    b    8.0

In [21]:
# right等价于数据库的right join
pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2', how='right')

  key1  data1 key2  data2
0    a    1.0    a      0
1    a    9.0    a      0
2    a    3.0    a      0
3    b    2.0    b      8
4    b    6.0    b      8
5    b    1.0    b      8
6  NaN    NaN    d      2

In [22]:
# 处理重复列名
df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data' : np.random.randint(0,10,7)})
df_obj2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                        'data' : np.random.randint(0,10,3)})
#给相同的数据列添加后缀
print(pd.merge(df_obj1, df_obj2, on='key', suffixes=('_left', '_right')))

  key  data_left  data_right
0   b          8           6
1   b          6           6
2   a          6           0
3   a          3           0
4   a          8           0
5   b          4           6

In [23]:
# 按索引连接
df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data1' : np.random.randint(0,10,7)})
df_obj2 = pd.DataFrame({'data2' : np.random.randint(0,10,3)}, index=['a', 'b', 'd'])
print(df_obj1)
print(df_obj2)

  key  data1
0   b      2
1   b      9
2   a      1
3   c      1
4   a      6
5   a      4
6   b      2
   data2
a      3
b      6
d      6

In [24]:
print(pd.merge(df_obj1, df_obj2, left_on='key', right_index=True))

  key  data1  data2
0   b      2      6
1   b      9      6
2   a      1      3
4   a      6      3
5   a      4      3
6   b      2      6

In [25]:
pd.merge(df_obj2,df_obj1, left_index=True, right_on='key')

   data2 key  data1
2      3   a      1
4      3   a      6
5      3   a      4
0      6   b      2
1      6   b      9
6      6   b      2